Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2018-12, with the labels that each got.

#225 doxygen hotfix
  Makefile
  doc/cmsgemos.cfg
Labels: PR: reviewed-approved, Type: Bugfix

#227 Update Makefile for building docs
  Makefile
  doc/cmsgemos.cfg
Labels: PR: reviewed-approved, Priority: Low

#222 Online DB configuration objects
  gemonlinedb/.gitignore
  gemonlinedb/Makefile
  gemonlinedb/defs/VFAT3ChipConfiguration.json
  gemonlinedb/include/gem/onlinedb/ConfigurationTraits.h
  gemonlinedb/include/gem/onlinedb/DataSet.h
  gemonlinedb/include/gem/onlinedb/PartReference.h
  gemonlinedb/include/gem/onlinedb/Run.h
  gemonlinedb/include/gem/onlinedb/VFAT3ChannelConfiguration.h
  gemonlinedb/include/gem/onlinedb/VFAT3ChipConfiguration.h
  gemonlinedb/include/gem/onlinedb/XMLSerializationData.h
  gemonlinedb/include/gem/onlinedb/detail/README.md
  gemonlinedb/include/gem/onlinedb/detail/RegisterData.h
  gemonlinedb/include/gem/onlinedb/detail/XMLUtils.h
  gemonlinedb/parseDef.py
  gemonlinedb/src/common/Run.cc
  gemonlinedb/src/common/VFAT3ChannelConfiguration.cc
  gemonlinedb/src/common/XMLSerializationData.cc
  gemonlinedb/src/common/XMLUtils.cc
  gemonlinedb/test/testVFAT3ChannelConfiguration.cc
  gemonlinedb/test/testXMLSerialization.cc
  gemonlinedb/xml/VFAT3_Chip_Configuration.xml
  gemonlinedb/xml/schema/common.xsd
Labels: PR: reviewed-approved
