Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2018-02, with the labels that each got.

#158 New Feature: xhal & RPC functionality added to gempython
  gempython/tests/vfat_info_xhal.py
  gempython/tools/amc_user_functions_xhal.py
  gempython/tools/optohybrid_user_functions_xhal.py
  gempython/tools/vfat_user_functions_xhal.py
  setup/etc/addresstables/connections_tif.xml
Labels: Status: Blocked, Status: Revision Needed

#168 Bring in travis and gitlab CI functionality
  .codecov.yml
  .coveralls.yml
  .github/.gitignore
  .github/ISSUE_TEMPLATE.md
  .gitignore
  .gitlab-ci.yml
  .travis.yml
  .travis/.gitignore
  .travis/cmsgemos-deploy-key.enc
  .travis/docker.sh
  .travis/travis.sh
  CHANGELOG.rst
  CONTRIBUTORS.rst
  README.md
  README.rst
  RELEASE.rst
  config/gemostag
  cpplint.py
  setup/etc/profile.d/xdaqenv.sh
  setup/paths.sh
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Maintenance

#171 Changed sturdy/jsturdy specifics to cms-gem-daq-project
  .gitlab-ci.yml
  .travis.yml
  .travis/travis.sh
  README.md
Labels: Type: Maintenance
