Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2018-08, with the labels that each got.

#192 New Feature: Get Channel Registers for VFAT3 [V3]
  gempython/tools/vfat_user_functions_xhal.py
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#195 New Feature: Check Sbit Mapping and Rate [V3]
  gempython/tools/optohybrid_user_functions_xhal.py
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#199 Bug Fix: Compile Error Mentioned in #198
  gemhardware/src/common/HwGenericAMC.cc
Labels: Priority: High, Type: Bugfix

#200 add missing postinstallrpm.sh
  gempython/pkg/postinstallrpm.sh
Labels: Type: Bugfix
