Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2018-10, with the labels that each got.

#205 Develop daq monitoring
  Makefile
  gemdaqmonitor/html/css/bootstrap 2.css
  gemdaqmonitor/html/css/bootstrap-theme.css
  gemdaqmonitor/html/css/bootstrap-theme.min.css
  gemdaqmonitor/html/css/bootstrap.css
  gemdaqmonitor/html/css/bootstrap.min 2.css
  gemdaqmonitor/html/css/bootstrap.min.css
  gemdaqmonitor/html/css/portfolio-item.css
  gemdaqmonitor/html/css/simple-sidebar.css
  gemdaqmonitor/html/css/style.css
  gemdaqmonitor/html/scripts/bootstrap.js
  gemdaqmonitor/html/scripts/bootstrap.min.js
  gemdaqmonitor/html/scripts/jquery.js
  gemdaqmonitor/html/scripts/npm.js
  gemdaqmonitor/html/scripts/shelfMonitor.js
  gemdaqmonitor/html/scripts/system_overview.js
  gemdaqmonitor/include/gem/daqmon/DaqMonitor.h
  gemdaqmonitor/include/gem/daqmon/ShelfMonitorWeb.h
  gemdaqmonitor/src/common/DaqMonitor.cc
  gemdaqmonitor/src/common/ShelfMonitorWeb.cc
  setup/make_xdaq_softlinks.sh
Labels: Priority: High, Status: Completed, Status: Review Needed, Type: Enhancement

#209 Removing possibility to scan CFG_IREF from dac scans
  gempython/tools/amc_user_functions_xhal.py
Labels: Priority: High, Type: Bugfix

#210 Develop daq monitoring
  gemdaqmonitor/Makefile
  gemdaqmonitor/html/scripts/shelfMonitor.js
  gemdaqmonitor/include/gem/daqmon/DaqMonitor.h
  gemdaqmonitor/include/gem/daqmon/ShelfMonitor.h
  gemdaqmonitor/include/gem/daqmon/ShelfMonitorWeb.h
  gemdaqmonitor/src/common/DaqMonitor.cc
  gemdaqmonitor/src/common/ShelfMonitor.cc
  gemdaqmonitor/src/common/ShelfMonitorWeb.cc
Labels: PR: reviewed-approved, Priority: Medium

#211 change <TYPE> logging macros to CMSGEMOS_<TYPE>
  gembase/src/common/GEMApplication.cc
  gembase/src/common/GEMFSM.cc
  gembase/src/common/GEMFSMApplication.cc
  gembase/src/common/GEMMonitor.cc
  gembase/src/common/GEMWebApplication.cc
  gembase/src/common/utils/GEMInfoSpaceToolBox.cc
  gemdaqmonitor/src/common/DaqMonitor.cc
  gemdaqmonitor/src/common/ShelfMonitor.cc
  gemdaqmonitor/src/common/ShelfMonitorWeb.cc
  gemhardware/include/gem/hw/optohybrid/HwOptoHybrid.h
  gemhardware/src/common/GEMHwDevice.cc
  gemhardware/src/common/HwGenericAMC.cc
  gemhardware/src/common/amc13/AMC13Manager.cc
  gemhardware/src/common/amc13/AMC13ManagerWeb.cc
  gemhardware/src/common/amc13/AMC13Readout.cc
  gemhardware/src/common/ctp7/CTP7Manager.cc
  gemhardware/src/common/ctp7/CTP7ManagerWeb.cc
  gemhardware/src/common/ctp7/CTP7Monitor.cc
  gemhardware/src/common/ctp7/CTP7Readout.cc
  gemhardware/src/common/ctp7/HwCTP7.cc
  gemhardware/src/common/glib/GLIBManager.cc
  gemhardware/src/common/glib/GLIBManagerWeb.cc
  gemhardware/src/common/glib/GLIBMonitor.cc
  gemhardware/src/common/glib/GLIBReadout.cc
  gemhardware/src/common/glib/HwGLIB.cc
  gemhardware/src/common/optohybrid/HwOptoHybrid.cc
  gemhardware/src/common/optohybrid/OptoHybridManager.cc
  gemhardware/src/common/optohybrid/OptoHybridManagerWeb.cc
  gemhardware/src/common/optohybrid/OptoHybridMonitor.cc
  gemhardware/src/common/utils/GEMCrateUtils.cc
  gemhardware/src/common/vfat/HwVFAT2.cc
  gemhardware/src/common/vfat/VFATManager.cc
  gemreadout/src/common/GEMDataParker.cc
  gemreadout/src/common/GEMReadoutApplication.cc
  gemreadout/src/common/GEMReadoutWebApplication.cc
  gemsupervisor/src/common/GEMGLIBSupervisorWeb.cc
  gemsupervisor/src/common/GEMGlobalState.cc
  gemsupervisor/src/common/GEMSupervisor.cc
  gemsupervisor/src/common/GEMSupervisorMonitor.cc
  gemsupervisor/src/common/GEMSupervisorWeb.cc
  gemsupervisor/src/common/tbutils/GEMTBUtil.cc
  gemsupervisor/src/common/tbutils/LatencyScan.cc
  gemsupervisor/src/common/tbutils/ThresholdScan.cc
  gemutils/include/gem/utils/GEMLogging.h
  gemutils/include/gem/utils/soap/GEMSOAPToolBox.h
  gemutils/src/common/db/GEMDatabaseUtils.cc
  gemutils/src/common/gemXMLparser.cc
  gemutils/src/common/soap/GEMSOAPToolBox.cc
Labels: PR: reviewed-approved, Priority: Medium, Type: Maintenance

#212 fix remaining migrations to CMSGEMOS_<TYPE> logger macros
  gemdaqmonitor/src/common/DaqMonitor.cc
  gemdaqmonitor/src/common/ShelfMonitor.cc
Labels: PR: reviewed-approved, Type: Bugfix
