Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2019-07, with the labels that each got.

#287 Feature/ge21compatibility
  gempython/tools/amc_user_functions_xhal.py
  gempython/tools/hw_constants.py
  gempython/tools/optohybrid_user_functions_xhal.py
  gempython/tools/vfat_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: Medium, Status: Review Needed, Type: Enhancement

#294 [bugfix] Fix #291: Invalid default value in HwVFAT::stopCalPulses
  gempython/tools/vfat_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: Medium, Status: Review Needed, Type: Bugfix, Type: Maintenance

#296 Add default GBT RX phases for long GE1/1 GEBs
  gempython/tools/hw_constants.py
Labels: PR: reviewed-approved, Priority: Critical, Type: Enhancement, Type: Maintenance

#298 HwVFAT::biasAllVFATs(...) will now throw an exception if RPC response is nonzero (Implementing Feature Request #295)
  gempython/tools/vfat_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: Medium, Type: Feature Request

#301 Bug Fix: wrong RunType value assigned for latency scans
  gempython/tools/xdaq/set_scanParams_latency.py
Labels: PR: reviewed-approved, Priority: Medium, Type: Bugfix
