Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2019-06, with the labels that each got.

#282 Updated assignment of number of GBTs for different gemTypes
  gempython/tools/amc_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: High, Type: Enhancement

#283 #280: Update writeGBTPhase.py for single/multiple links
  gempython/tests/writeGBTPhase.py
Labels: PR: reviewed-approved, Priority: High, Status: Accepted, Type: Enhancement

#285 All bits of SCA MONITORING_OFF register are 1
  gempython/tools/amc_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: Critical

#286 Bug Fix: HwAMC should be using self.NGBT not NGBT
  gempython/tools/amc_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: High, Type: Bugfix

#288 [feature] HW device migration
  gemHwMonitor/include/gem/hwMonitor/gemHwMonitorBase.h
  gembase/include/gem/base/GEMApplication.h
  gembase/include/gem/base/GEMFSMApplication.h
  gembase/include/gem/base/utils/GEMInfoSpaceToolBox.h
  gembase/src/common/GEMFSMApplication.cc
  gemhardware/Makefile.managers
  gemhardware/include/gem/hw/GEMHwDevice.h
  gemhardware/include/gem/hw/HwGenericAMC.h
  gemhardware/include/gem/hw/ctp7/HwCTP7.h
  gemhardware/include/gem/hw/exception/Exception.h
  gemhardware/include/gem/hw/glib/GLIBManager.h
  gemhardware/include/gem/hw/glib/HwGLIB.h
  gemhardware/include/gem/hw/optohybrid/HwOptoHybrid.h
  gemhardware/include/gem/hw/optohybrid/OptoHybridManager.h
  gemhardware/include/gem/hw/optohybrid/OptoHybridMonitor.h
  gemhardware/include/gem/hw/optohybrid/OptoHybridSettingsEnums.h
  gemhardware/src/common/GEMHwDevice.cc
  gemhardware/src/common/HwGenericAMC.cc
  gemhardware/src/common/ctp7/CTP7Manager.cc
  gemhardware/src/common/ctp7/HwCTP7.cc
  gemhardware/src/common/glib/GLIBManager.cc
  gemhardware/src/common/glib/GLIBMonitor.cc
  gemhardware/src/common/glib/HwGLIB.cc
  gemhardware/src/common/optohybrid/HwOptoHybrid.cc
  gemhardware/src/common/optohybrid/OptoHybridManager.cc
  gemhardware/src/common/optohybrid/OptoHybridMonitor.cc
  gempython/__init__.py
  gempython/src/common/cmsgemos_gempython.cc
  gempython/tests/amc_info.py
  gempython/tests/optohybrid_info.py
  gempython/tests/vfat_info.py
  gempython/tools/amc_user_functions.py
  gempython/tools/glib_system_info_uhal.py
  gempython/tools/optohybrid_user_functions.py
  gempython/utils/db/ldqm_db/amcmanager.py
  gempython/utils/gemlogger.py
  gempython/utils/gemlogging_config.cfg
  gempython/utils/registers_uhal.py
  gemsupervisor/xml/gemsupervisor.xml
  gemutils/Makefile
  gemutils/include/gem/utils/GEMRegisterUtils.h
  gemutils/src/common/GEMRegisterUtils.cc
Labels: PR: unreviewed, Priority: High, Type: Enhancement
