Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2019-03, with the labels that each got.

#255 Fix gemonlinedb build
  gemonlinedb/include/gem/onlinedb/AMCConfiguration.h
  gemonlinedb/include/gem/onlinedb/OHv3Configuration.h
  gemonlinedb/include/gem/onlinedb/VFAT3ChipConfiguration.h
  gemonlinedb/xml/schema/AMC13Configuration.xsd
Labels: PR: reviewed-approved

#256 Update XHAL path
  gemdaqmonitor/Makefile
  gemhardware/Makefile.devices
  gemhardware/Makefile.managers
  gempython/Makefile
  gemsupervisor/Makefile
Labels: PR: reviewed-approved, Type: Bugfix

#258 New Feature: automatic determination of shelf and slot at initialization
  gempython/tools/amc_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: Medium, Status: Review Needed, Type: Enhancement

#262 Bug Fix: attribute error in set_scanParams_latency.py due to a legacy keyword
  gempython/tools/xdaq/set_scanParams_latency.py
Labels: Priority: Critical, Type: Bugfix

#266 [feature] OnlineDB ConfigurationManager
  gemonlinedb/Makefile
  gemonlinedb/include/gem/onlinedb/ConfigurationManager.h
  gemonlinedb/include/gem/onlinedb/detail/XMLUtils.h
  gemonlinedb/include/gem/onlinedb/exception/Exception.h
  gemonlinedb/include/gem/onlinedb/gemonlinedb.h
  gemonlinedb/src/common/ConfigurationManager.cc
  gemonlinedb/src/common/FileUtils.cc
  gemonlinedb/src/common/XMLUtils.cc
  gemonlinedb/test/testAMC13Configuration.cc
  gemonlinedb/test/testConfigurationLinker.cc
  gemonlinedb/test/testConfigurationManager.cc
  gemonlinedb/test/testSystemTopology.cc
  gemonlinedb/test/testXMLSerialization.cc
Labels: PR: reviewed-approved, Priority: High, Type: Enhancement, Type: Feature Request

#263 Add link status check to test connectivity
  gempython/tools/amc_user_functions_xhal.py
Labels: PR: reviewed-approved
