Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2019-05, with the labels that each got.

#275 Gemcalibration package second PR
  Makefile
  config/mfPythonDefsGEM.mk
  gembase/html/css/bootstrap.css
  gembase/html/css/bootstrap.min.css
  gembase/html/scripts/bootstrap.js
  gembase/html/scripts/bootstrap.min.js
  gembase/html/scripts/jquery.min.js
  gemcalibration/Makefile
  gemcalibration/html/scripts/cal_routines.js
  gemcalibration/include/gem/calib/Calibration.h
  gemcalibration/include/gem/calib/CalibrationWeb.h
  gemcalibration/include/gem/calib/GEMCalibEnums.h
  gemcalibration/src/common/Calibration.cc
  gemcalibration/src/common/CalibrationWeb.cc
  gemcalibration/xml/gemcalibration.xml
  gemdaqmonitor/Makefile
  gemhardware/Makefile.devices
  gemhardware/Makefile.managers
  gempython/Makefile
  gemsupervisor/Makefile
  setup/etc/profile.d/gemdaqenv.sh
Labels: PR: reviewed-approved, Priority: High, Type: Enhancement

#276 OnlineDB monitoring page
  gemonlinedb/Makefile
  gemonlinedb/html/scripts/gemonlinedb.js
  gemonlinedb/include/gem/onlinedb/ConfigurationManager.h
  gemonlinedb/include/gem/onlinedb/ConfigurationProvider.h
  gemonlinedb/include/gem/onlinedb/XMLConfigurationProvider.h
  gemonlinedb/src/common/ConfigurationManager.cc
  gemonlinedb/src/common/GEMOnlineDBManagerWeb.cc
  gemonlinedb/src/common/XMLConfigurationProvider.cc
Labels: PR: reviewed-approved

#249 [feature] Add GBTX configuration objects
  gemonlinedb/Makefile
  gemonlinedb/defs/AMCConfiguration.json
  gemonlinedb/defs/GBTXConfiguration.json
  gemonlinedb/defs/OHv3Configuration.json
  gemonlinedb/include/gem/onlinedb/AMCConfiguration.h
  gemonlinedb/include/gem/onlinedb/ConfigurationProvider.h
  gemonlinedb/include/gem/onlinedb/GBTXConfiguration.h
  gemonlinedb/include/gem/onlinedb/OHv3Configuration.h
  gemonlinedb/include/gem/onlinedb/SystemTopology.h
  gemonlinedb/include/gem/onlinedb/XMLConfigurationProvider.h
  gemonlinedb/parseDef.py
  gemonlinedb/src/common/AMCConfiguration.cc
  gemonlinedb/src/common/ConfigurationLinker.cc
  gemonlinedb/src/common/OHv3Configuration.cc
  gemonlinedb/src/common/SystemTopology.cc
  gemonlinedb/src/common/XMLConfigurationProvider.cc
  gemonlinedb/xml/examples/GBTX_Configuration.xml
  gemonlinedb/xml/examples/system-topology.xml
  gemonlinedb/xml/schema/system-topology.xsd
Labels: PR: unreviewed, Status: On Hold

#273 New Feature: Program OH FW and automatic ohMask determination
  gempython/tests/writeGBTPhase.py
  gempython/tools/amc_user_functions_xhal.py
  gempython/tools/hw_constants.py
  gempython/tools/optohybrid_user_functions_xhal.py
  gempython/tools/vfat_user_functions_xhal.py
  gempython/tools/xdaq/setDAQParamsPostConfigure.py
  gempython/utils/wrappers.py
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Enhancement

#281 Updates for legacy uhal info scripts
  gempython/tests/amc_info_uhal.py
  gempython/tests/optohybrid_info_uhal.py
  gempython/tests/vfat_info_uhal.py
  gempython/tools/amc_user_functions_uhal.py
  gempython/tools/amc_user_functions_xhal.py
  gempython/tools/hw_constants.py
  gempython/tools/optohybrid_user_functions_uhal.py
  gempython/tools/vfat_user_functions_uhal.py
  gempython/utils/registers_uhal.py
Labels: PR: reviewed-approved, Priority: High, Type: Feature Request, Type: Maintenance
