Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2019-02, with the labels that each got.

#238 Add HW layout object
  gemonlinedb/.gitignore
  gemonlinedb/Makefile
  gemonlinedb/include/gem/onlinedb/ConfigurationLinker.h
  gemonlinedb/include/gem/onlinedb/ConfigurationProvider.h
  gemonlinedb/include/gem/onlinedb/SystemTopology.h
  gemonlinedb/include/gem/onlinedb/XMLConfigurationProvider.h
  gemonlinedb/include/gem/onlinedb/XMLSerializationData.h
  gemonlinedb/include/gem/onlinedb/detail/FileUtils.h
  gemonlinedb/include/gem/onlinedb/detail/XMLUtils.h
  gemonlinedb/include/gem/onlinedb/exception/Exception.h
  gemonlinedb/src/common/AMC13Configuration.cc
  gemonlinedb/src/common/ConfigurationLinker.cc
  gemonlinedb/src/common/FileUtils.cc
  gemonlinedb/src/common/SystemTopology.cc
  gemonlinedb/src/common/XMLConfigurationProvider.cc
  gemonlinedb/src/common/XMLSerializationData.cc
  gemonlinedb/src/common/XMLUtils.cc
  gemonlinedb/test/testAMC13Configuration.cc
  gemonlinedb/test/testConfigurationLinker.cc
  gemonlinedb/test/testFileUtils.cc
  gemonlinedb/test/testSystemTopology.cc
  gemonlinedb/test/testVFAT3ChannelConfiguration.cc
  gemonlinedb/test/testXMLConfigurationProvider.cc
  gemonlinedb/test/testXMLSerialization.cc
  gemonlinedb/xml/VFAT3_Chip_Configuration.xml
  gemonlinedb/xml/examples/AMC13_Configuration.xml
  gemonlinedb/xml/examples/AMC_Configuration.xml
  gemonlinedb/xml/examples/OHv3_Configuration.xml
  gemonlinedb/xml/examples/VFAT3_Channel_Configuration.xml
  gemonlinedb/xml/examples/VFAT3_Chip_Configuration.xml
  gemonlinedb/xml/examples/system-topology.xml
  gemonlinedb/xml/schema/system-topology.xsd
Labels: PR: reviewed-approved

#239 [new feature] onlinedb web UI
  Makefile
  gemonlinedb/Makefile
  gemonlinedb/html/scripts/gemonlinedb.js
  gemonlinedb/include/gem/onlinedb/GEMOnlineDBManager.h
  gemonlinedb/include/gem/onlinedb/GEMOnlineDBManagerWeb.h
  gemonlinedb/src/common/GEMOnlineDBManager.cc
  gemonlinedb/src/common/GEMOnlineDBManagerWeb.cc
  gemonlinedb/xml/gemonlinedbmanager.xml
  setup/make_xdaq_softlinks.sh
  setup/paths.sh
Labels: PR: unreviewed, Priority: Medium, Type: Enhancement

#237 Populate configuration objects from TStore result
  gemonlinedb/Makefile
  gemonlinedb/include/gem/onlinedb/AMC13Configuration.h
  gemonlinedb/include/gem/onlinedb/DBInterface.h
  gemonlinedb/src/common/AMC13Configuration.cc
  gemonlinedb/src/common/DBInterface.cc
  gemonlinedb/src/common/VFAT3ChannelConfiguration.cc
  gemonlinedb/test/testTStoreSerialization.cc
  gemonlinedb/test/testVFAT3ChannelConfiguration.cc
  gemonlinedb/xml/examples/VFAT3_Channel_Configuration.xml
  gemonlinedb/xml/schema/VFAT3ChannelConfiguration.xsd
Labels: PR: unreviewed

#242 Fix #240
  Makefile
  gemonlinedb/Makefile
Labels: PR: reviewed-approved, Type: Bugfix

#243 [feature] Update build system to be able to run tests on CI
  Makefile
  config/mfDefsGEM.mk
  gemonlinedb/Makefile
Labels: PR: reviewed-approved

#246 New Feature: Python Tools for Connectivity Testing
  gempython/tools/amc_user_functions_uhal.py
  gempython/tools/amc_user_functions_xhal.py
  gempython/tools/optohybrid_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: Medium, Type: Enhancement

#250 Hot Fix: Updated VFAT_MASK Register Node Name in FPGA
  gempython/tools/optohybrid_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: High, Type: Bugfix, Type: Maintenance

#253 [Hotfix] Bug Fix: Resolved a NameError in printSystemSCAInfo()
  gempython/tools/amc_user_functions_uhal.py
Labels: PR: reviewed-approved, Priority: High, Type: Bugfix, Type: Maintenance
