Repository cms-gem-daq-project/cmsgemos, pull requests merged in 2019-04, with the labels that each got.

#260 New Feature: sbit rate scan considers all links at once
  gempython/tools/amc_user_functions_xhal.py
  gempython/tools/optohybrid_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Enhancement

#257 New Feature: HwVFAT::getAllChipIDs(...) now uses RPC Function
  gempython/tools/vfat_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: High, Status: Review Needed, Type: Enhancement

#269 Bug Fix: resolving issue 268
  gempython/tools/amc_user_functions_xhal.py
Labels: PR: reviewed-approved, Priority: Critical, Status: Review Needed, Type: Bugfix

#277 Fix horizontal scrolling in GEM applications
  gembase/html/css/gemwebapp.css
  gembase/html/scripts/gemwebapp.js
Labels: PR: reviewed-approved
